# Generated by Django 3.2.9 on 2021-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='year_in_school',
            field=models.CharField(choices=[('P', 'In Progress'), ('F', 'Finished')], default='P', max_length=2),
        ),
    ]
