# Generated by Django 3.2.9 on 2021-11-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='year_in_school',
            new_name='state',
        ),
    ]
