# Generated by Django 3.2.9 on 2021-11-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_year_in_school_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='IN PROGRESS', max_length=12),
        ),
    ]
