# Generated by Django 3.2.9 on 2021-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_slug'),
        ('tasks', '0003_remove_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(default=None, to='tags.Tag'),
        ),
    ]
