# Generated by Django 3.2.9 on 2021-11-22 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ALERT', 'This is just an alert'), ('IMPORTANT', 'This is very important '), ('MUST', 'This must be done at the end of the day'), ('CRITICAL', 'This is already delayed')], default='ALERT', max_length=12)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
